<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="111466" started-at="2019-06-05T09:55:58Z" finished-at="2019-06-05T09:57:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="111466" started-at="2019-06-05T09:55:58Z" finished-at="2019-06-05T09:57:49Z">
      <class name="TestCases.MyPorfolioTest">
        <test-method status="PASS" signature="openPorfolio(java.util.Hashtable)[pri:0, instance:TestCases.MyPorfolioTest@64485a47]" name="openPorfolio" duration-ms="35699" started-at="2019-06-05T09:55:59Z" data-provider="getOpenPortfolioTestData" finished-at="2019-06-05T09:56:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Test@1234, PageTitle=Rediff Moneywiz | My Portfolio(s), Comment=Valid Credentials, UserName=anshulc55}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPorfolio -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.MyPorfolioTest@64485a47]" name="flushReports" is-config="true" duration-ms="638" started-at="2019-06-05T09:56:34Z" finished-at="2019-06-05T09:56:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="FAIL" signature="openPorfolio(java.util.Hashtable)[pri:0, instance:TestCases.MyPorfolioTest@64485a47]" name="openPorfolio" duration-ms="32188" started-at="2019-06-05T09:56:35Z" data-provider="getOpenPortfolioTestData" finished-at="2019-06-05T09:57:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Anshul@123, PageTitle=Indian stock markets: Login to Portfolio, Comment=Invalid Password, UserName=anshulc55}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is failed on Portfolio Login Page]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is failed on Portfolio Login Page
at org.testng.Assert.fail(Assert.java:96)
at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:67)
at PageClasses.PortFolioLoginPage.doLogin(PortFolioLoginPage.java:58)
at TestCases.MyPorfolioTest.openPorfolio(MyPorfolioTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPorfolio -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.MyPorfolioTest@64485a47]" name="flushReports" is-config="true" duration-ms="232" started-at="2019-06-05T09:57:07Z" finished-at="2019-06-05T09:57:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="FAIL" signature="verifyLogin(java.util.Hashtable)[pri:0, instance:TestCases.MyPorfolioTest@64485a47]" name="verifyLogin" duration-ms="24002" started-at="2019-06-05T09:57:08Z" data-provider="verifyLoginTestData" finished-at="2019-06-05T09:57:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Test@1234, PageTitle=Indian stock markets: Login to Portfolio, Comment=Invalid UserName, UserName=anshulc}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Password box is not appeared]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Password box is not appeared
at org.testng.Assert.fail(Assert.java:96)
at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:67)
at baseClasses.PageBaseClass.veriyElementIsDisplayed(PageBaseClass.java:54)
at PageClasses.PortFolioLoginPage.verifyPasswordField(PortFolioLoginPage.java:90)
at TestCases.MyPorfolioTest.verifyLogin(MyPorfolioTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.MyPorfolioTest@64485a47]" name="flushReports" is-config="true" duration-ms="297" started-at="2019-06-05T09:57:32Z" finished-at="2019-06-05T09:57:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="FAIL" signature="verifyLogin(java.util.Hashtable)[pri:0, instance:TestCases.MyPorfolioTest@64485a47]" name="verifyLogin" duration-ms="17330" started-at="2019-06-05T09:57:32Z" data-provider="verifyLoginTestData" finished-at="2019-06-05T09:57:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Password=Anshul@123, PageTitle=Indian stock markets: Login to Portfolio, Comment=Invalid Credentials, UserName=anshulc}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Password box is not appeared]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Password box is not appeared
at org.testng.Assert.fail(Assert.java:96)
at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:67)
at baseClasses.PageBaseClass.veriyElementIsDisplayed(PageBaseClass.java:54)
at PageClasses.PortFolioLoginPage.verifyPasswordField(PortFolioLoginPage.java:90)
at TestCases.MyPorfolioTest.verifyLogin(MyPorfolioTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.MyPorfolioTest@64485a47]" name="flushReports" is-config="true" duration-ms="252" started-at="2019-06-05T09:57:49Z" finished-at="2019-06-05T09:57:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
      </class> <!-- TestCases.MyPorfolioTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
